# This file was generated by GoReleaser. DO NOT EDIT.
cask "marathon" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "09a9c5400e19defcf60a3c0eafc643618db38f6ab99b4baeea97d53b2d659f53"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d29419241cf70657ab9f7437fe398aa2f42550994cd0df517fdf5b5603d86131"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8117ab1ca645f1b7a57a6dd135b2e8f1b74b969152fa8b95e7ec90f1a6048520"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c858da132aa3a86197a0adb8af5f2c193bf87db88b81b4a1b0a5e384a047763d"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Linux_arm64.tar.gz"
    end
  end

  name "marathon"
  desc "CLI/TUI for viewing, managing, and running markdown runbooks"
  homepage "https://github.com/a-poor/marathon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marathon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marathon"]
    end
  end
  generate_completions_from_executable "marathon", "completions",
    base_name: "marathon",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
