# This file was generated by GoReleaser. DO NOT EDIT.
cask "marathon" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "a1f6ad556a994483ad3f5637ac68481f6f5a878fd9cad2d38bf683fa5e008247"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8c1456b451ead2422860b542750f1f122c5533fda173820f6eda035e75cc78e6"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6c9197593c443b0976321f78d34217a7e275ecfe8edeb117032a27c7512918d"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "885c4090f996d83911b55776d8202fb043c4b39aea44e891d09ebe6980027249"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Linux_arm64.tar.gz"
    end
  end

  name "marathon"
  desc "CLI/TUI for viewing, managing, and running markdown runbooks"
  homepage "https://github.com/a-poor/marathon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marathon"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marathon"]
    end
  end

  # No zap stanza required

end
