# This file was generated by GoReleaser. DO NOT EDIT.
cask "marathon" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "be364126a3dfab6b1858468c459b8caef78d19aa96343b92cfd41fd39c9a5831"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a5476a4aae576b0d4875974e5bbb9e6f660cf6c7091b14d4b331a2697679dc60"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "80b691b3df5e745990dabd95bddefdfc071283ca9b272dfba7c48513f6f48326"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1462e41bf392ca9e1730ed07403dd3b9220ec0f23d6bcd8b77a0a49fe549a0e5"
      url "https://github.com/a-poor/marathon/releases/download/v#{version}/marathon_Linux_arm64.tar.gz"
    end
  end

  name "marathon"
  desc "CLI/TUI for viewing, managing, and running markdown runbooks"
  homepage "https://github.com/a-poor/marathon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "marathon"
  bash_completion "completions/marathon.bash"
  fish_completion "completions/marathon.fish"
  zsh_completion "completions/marathon.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/marathon"]
    end
  end

  # No zap stanza required

end
